# Generated by Django 3.1.6 on 2021-05-01 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_portfolio', '0002_project_github_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='heroku_url',
        ),
    ]
