# Generated by Django 3.1.6 on 2021-05-03 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_portfolio', '0003_remove_project_heroku_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='github_url',
            new_name='url',
        ),
    ]
